function producer = createProducer(initialCapital,T,strategy,rigs)
%Create Producer: The producer is represented by a struct:
% capital: the producer's capital. 
% ROC: The "Return Of Capital"
% wells: An array of wells run by the producer. The producer starts with 
% an empty array.

drillTime = 1;         % [month] Default
compTime = 1;         % [month] Default
numWells = zeros(T,1); % An array with number of total wells at time t. 
newWells = zeros(T,1); % An array with number of wells drilled at time t. 
capital = zeros(T,1);  % An array with capital/cash at time t. 
capital(1) =  initialCapital;
wells = [];            % An array to store all the wells-structs. 
totalProd = zeros(T,1);
anticipatedProdAdd = zeros(T,1);
wellsPerRigRate = ones(T,1);
NPVaggrConserv = zeros(T,1);
prodAim         = zeros(T,1);
cutOffProd = 20;

if(~exist('rigs','var') || nargin<4)
    rigs = zeros(T,1);
end

investInput       = constructInputs();
NPVestimatorInput = constructInputs();

producer = struct('capital',capital,...
    'wells',wells,...
    'numWells',numWells,...
    'newWells',newWells,...
    'strategy',strategy,...
    'rigs',rigs,...
    'drillTime',drillTime,...
    'compTime',compTime,...
    'totalProd',totalProd,...
    'anticipatedProdAdd',anticipatedProdAdd,...
    'investInput',investInput,...
    'NPVestimatorInput',NPVestimatorInput,...
    'NPVaggrConserv',NPVaggrConserv,...
    'prodAim',prodAim,...
    'wellsPerRigRate',wellsPerRigRate,...
    'cutOffProd',cutOffProd);
end

